// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 711 06/05/2020)
// Created on Fri Nov 20 23:10:21 2020

m4_input m4_input_inst
(
	.hsync(hsync_sig) ,	// input  hsync_sig
	.vsync(vsync_sig) ,	// input  vsync_sig
	.video(video_sig) ,	// input  video_sig
	.waddr(waddr_sig) ,	// output [17:0] waddr_sig
	.dotclk(dotclk_sig) ,	// input  dotclk_sig
	.pixel_state(pixel_state_sig) ,	// output  pixel_state_sig
	.wren(wren_sig) ,	// output  wren_sig
	.leds0(leds0_sig) ,	// output  leds0_sig
	.leds1(leds1_sig) ,	// output  leds1_sig
	.leds2(leds2_sig) ,	// output  leds2_sig
	.leds3(leds3_sig) 	// output  leds3_sig
);

